--- #YAML:1.0
name:                App-BCVI-AutoInstall
version:             0.1
abstract:            Automatically install bcvi on a new host
license:             ~
author:              
    - Andrew Ruthven <andrew@etc.gen.nz>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
